version: '3.8'
services:
  web:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    ports:
      - "3206:3206"
    volumes:
      - ../deploy:/app/../deploy:ro
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    restart: unless-stopped 